name: Native Image
on:
    push:
        branches:
            - main
    pull_request:
    release:
        types: [published]
jobs:
    unix:
        env:
            CI: true
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macOS-latest, ubuntu-latest, windows-latest]
                include:
                    - os: macOS-latest
                      uploaded_filename: htx-x86_64-apple-darwin
                      local_path: target/htx
                    - os: ubuntu-latest
                      uploaded_filename: htx-x86_64-pc-linux
                      local_path: target/htx
                    - os: windows-latest
                      uploaded_filename: htx-x86_64-pc-win32.exe
                      local_path: target\htx.exe
        steps:
            - uses: actions/checkout@v2
            - uses: olafurpg/setup-scala@v11
            - run: git fetch --tags || true
            - run: sbt cli/nativeImageCompressed
              shell: bash
              if: ${{ matrix.os != 'windows-latest' }}
            - run: echo $(pwd)
              shell: bash
            - name: (Windows) sbt cli/nativeImageCompressed
              shell: cmd
              if: ${{ matrix.os == 'windows-latest' }}
              run: >-
                  "C:\Program Files (x86)\Microsoft Visual
                  Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
                  cli/nativeImageCompressed
            - uses: actions/upload-artifact@v2
              with:
                  path: ${{ matrix.local_path }}
                  name: ${{ matrix.uploaded_filename }}
            - name: Upload release
              if: github.event_name == 'release'
              uses: actions/upload-release-asset@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ matrix.local_path }}
                  asset_name: ${{ matrix.uploaded_filename }}
                  asset_content_type: application/zip
